name: First Workflow
on: 
    push:


jobs:              
    hello-cowsay:
            needs: view-readme
            runs-on: ubuntu-latest
            steps:
                - name: Hello Step
                  run: echo "Hello world, from ${{ github.job }}"

                - name: Cowsay Step
                  run: ./script.sh
                
                    
    view-readme:                
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@4.2.2 

            - name: List and Read
              run: |
                ls -la

           # - name: cat dragon
            #  run: cat dragon.txt